spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MYSQL
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    format-sql: true
    hibernate:
      ddl-auto: create

