spring:
  jpa:
    show-sql: true

jasypt:
  encryptor:
    password: art_here_jasypt_key

---
spring:
  profiles:
    active: local

---
spring:
  profiles:
    group:
      set1: real-db
      set2: real-db
