spring:
  profiles:
    active: test

  jpa:
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(IU+Ra5VdMAWg207rEfiNzG3fMlmi7vskee2PMthvatTU1PZSo+I0BgHUVKCXZRGLHZOIJYCr9HD/GXA1akEkG8A8MwMAPvbWnaBbijAjrCoXBO0Dh7qFDw==)
            client-secret: ENC(6pD7u/p3IqYNn7QYtW5IihQWH/mEOW9GdJu63LltnBKyEHMCl3Kd4CD4bWIrKseK)
            scope:
              - profile
              - email

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(Lvg6XRoKO1Ah+l76VvqnBjndlhxNWgNbzyt8G//cLxjeAFBiBEKz9gNpcThcbk/pNcO1SJD7wRE2GRSIxoWcbrLQGADfHObTXhC7tdXtpFwlthkCY5kh+SYvN3H0CZUw)
    username: ENC(dJf9UFwvs+tYGAJ2yRRLJg==)
    password: ENC(DepIx46UuwHWFufWytFikXX6gncU9Y6UGS2x3eB/4zM=)

oauth:
  redirect-uri: https://art-here.site/oauth/success

security:
  jwt:
    token:
      secret-key: ENC(ohijKSt7tsZAm7dHHW/Mp15MHaahEqQ21qIx32Ug4841SIiWOsalDteer69+Gvf1PmgG8HOTaACRSvhaViWt3g==)
      access:
        expire-length: 3600000 # 1시간
      refresh:
        expire-length: 1209600000 # 2주

cloud:
  aws:
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false