spring:
  jpa:
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(IU+Ra5VdMAWg207rEfiNzG3fMlmi7vskee2PMthvatTU1PZSo+I0BgHUVKCXZRGLHZOIJYCr9HD/GXA1akEkG8A8MwMAPvbWnaBbijAjrCoXBO0Dh7qFDw==)
            client-secret: ENC(6pD7u/p3IqYNn7QYtW5IihQWH/mEOW9GdJu63LltnBKyEHMCl3Kd4CD4bWIrKseK)
            scope:
              - profile
              - email
oauth:
  redirect-uri: https://art-here.site/oauth/success

security:
  jwt:
    token:
      secret-key: ENC(ohijKSt7tsZAm7dHHW/Mp15MHaahEqQ21qIx32Ug4841SIiWOsalDteer69+Gvf1PmgG8HOTaACRSvhaViWt3g==)
      access:
        expire-length: 3600000 # 1시간
      refresh:
        expire-length: 1209600000 # 2주

aws:
  s3:
    bucket: ENC(0AClSBk5oQuvJUVYFRrSxg+yzNxE5bgvBoDldVNxy6E=)
    region: ENC(ovMoFG6VmdsVbj3GY6zLH4Ze0RDWLLfy)
  credentials:
    accessKey: ENC(bPe+s6Qdfbp9babO9iB9BRv9ve2nzm3dZgYanNkM/Ok=)
    secretKey: ENC(IU/VVNYkDtjMxFC9NaJu0svRz127W7aHHHK9h8FsIY9qD5JCqZFewU1X2WfqqCNeUZ0qyzKWJBA=)

  user:
    s3:
      bucket: ENC(vEGYXJ7McMBh9AqqRQP3xEt3B+ImWIGX)
      region:  ENC(ovMoFG6VmdsVbj3GY6zLH4Ze0RDWLLfy)
    credentials:
      accessKey: ENC(qM29kkeFXsM0ua7lv7ynJ60K3n/RWK0A49dg6DM1tZM=)
      secretKey: ENC(UIUJRDov66mdwlyXtCkiubG3JQYaT5pof2gXCe/QTQ1/5+fO/7KEnn886gZMo+LIhZeI0kP5Yrc=)

---
spring:
  profiles:
    active: local

---
spring:
  profiles:
    group:
      set1: prod
      set2: prod
