spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MYSQL
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    format-sql: true
    hibernate:
      ddl-auto: create

aws:
  s3:
    bucket: ENC(0AClSBk5oQuvJUVYFRrSxg+yzNxE5bgvBoDldVNxy6E=)
    region: ENC(ovMoFG6VmdsVbj3GY6zLH4Ze0RDWLLfy)
  credentials:
    accessKey: ENC(bPe+s6Qdfbp9babO9iB9BRv9ve2nzm3dZgYanNkM/Ok=)
    secretKey: ENC(IU/VVNYkDtjMxFC9NaJu0svRz127W7aHHHK9h8FsIY9qD5JCqZFewU1X2WfqqCNeUZ0qyzKWJBA=)

