spring:
  jpa:
    show-sql: true

jasypt:
  encryptor:
    password: art_here_jasypt_key

management:
  endpoints:
    web:
      exposure:
        include: "health"

---
spring:
  profiles:
    active: local

---
spring:
  profiles:
    group:
      set1: real-db
      set2: real-db
